spring:
  profiles:
    active: mysql  # Options: mysql, oracle
  
  datasource:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:3306}
    database: ${DB_NAME:payrep_db}
    username: ${DB_USERNAME:payrep}
    password: ${DB_PASSWORD:123456}
    
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  task:
    scheduling:
      pool:
        size: 5

# File Processing Configuration
file:
  processing:
    archive:
      enabled: true
    max:
      file:
        size: 100MB

logging:
  level:
    com.payrep: DEBUG
    org.springframework.scheduling: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080

---
# MySQL Profile Configuration
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---
# Oracle Profile Configuration
spring:
  config:
    activate:
      on-profile: oracle
  datasource:
    url: jdbc:oracle:thin:@${spring.datasource.host}:${spring.datasource.port:1521}:${spring.datasource.database}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
